# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - tecdu-web

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://tecduwebimage.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8e03904fd7054896a7b3bac53fb52f8e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ae76d6744a3442319ff96318cdffac05 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: tecduwebimage.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8e03904fd7054896a7b3bac53fb52f8e }}/testing:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tecdu-web'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_14ff98c701a048c5a2bdb73a53d8c015 }}
        images: 'tecduwebimage.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8e03904fd7054896a7b3bac53fb52f8e }}/testing:${{ github.sha }}'